### ISSUE TITLE
Current error with VRC Creator Companion 3.1.11

### ISSUE THREAD

**Issue by SchismGit** [blepmlem/VRChat-Expression-Utility#3]
![image](https://user-images.githubusercontent.com/10381039/223554859-f76bb817-3c46-43b9-af4e-3e3e3c45cdb8.png)

Text format:
Packages\com.blep.vrc-expression-utility\Editor\Utility.cs(33,5): error CS0103: The name 'ImageDownloader' does not exist in the current context

**Comment by blepmlem** [comment]
Fixed ❤️
