### ISSUE TITLE
Another Image namespace issue

### ISSUE THREAD

**Issue by SchismGit** [blepmlem/VRChat-Expression-Utility#4]
Sorry, Bleppy :(

Packages\blepmlem-VRChat-Expression-Utility-7745912\Editor\Utility.cs(15,16): error CS0234: The type or namespace name 'Image' does not exist in the namespace 'VRC.SDK3' (are you missing an assembly reference?)

**Comment by blepmlem** [comment]
This would be for projects on lower than current VRC Avatars SDK. The current version supports the newest version of the SDK only. I might try and make it backwards compatible at some point.
